### ISSUE TITLE
Spotify/Airplay not working

### ISSUE THREAD

**Issue by manwithpowers** [sweisgerber/docker-snapcast#9]
Hi,
I'm using the default docker-compose:
```
version: "3"
services:
  snapcast:
    image: docker.io/sweisgerber/snapcast:latest
    hostname: snapcast
    environment:
      - PUID=1000
      - PGID=1000 # set to audio group ID
      - TZ=Europe/Berlin
      - START_SNAPCLIENT=false # set to `true` for snapclient to start
      #  --host: name or ip of compose service or dockerhost
      # --soundcard: <ID> from `snapclient -l` from inside the container
      # - SNAPCLIENT_OPTS=--host snapcast --soundcard <ID>
      #   => Don't use quotes for SNAPCLIENT_OPTS="" !
      # - HOST_AUDIO_GROUP=<AUDIO-GID> # set to GID of host audio group
    restart: "unless-stopped"
    ports:
      - 1704:1704 # port for the actual audio streaming
      - 1705:1705 # port for TCP Json RPC
      - 1780:1780 # port for the SnapWeb Webinterface
    # devices:
      # - /dev/snd:/dev/snd # optional, only if you want to use snapclient
    volumes:
      - /srv/snapcast/config/:/config/
      - /srv/snapcast/data/:/data/
      # /audio should get used to place FIFOs for audio playback from mpd/mopidy/host/etc
      # /<path>/<to>/audio-fifos/:/audio/
```
and only modified the snapserver.conf with my Spotify info

but neither Spotify Connect nor Airplay are working (snapcast doesn't show up either in Spotify or in Apple Music).
In the docker container I'm seeing:
`snapcast-1  | 2024-04-12 15-09-05.535 [Error] (Avahi) Failed to create client: Daemon not running`
and
```
snapcast-1  | 2024-04-12 15-09-05.551 [Info] (AirplayStream) (Airplay) warning: couldn't create avahi client: Daemon not running!
snapcast-1  | 2024-04-12 15-09-05.551 [Info] (AirplayStream) (Airplay) fatal error: Could not establish mDNS advertisement!
```
```
snapcast-1  | 2024-04-12 15-09-10.549 [Warn] (librespot_core::apresolve) Failed to resolve Access Point: error trying to connect: dns error: failed to lookup address information: Try again
snapcast-1  | 2024-04-12 15-09-10.550 [Warn] (librespot_core::apresolve) Using fallback "ap.spotify.com:443"
snapcast-1  | 2024-04-12 15-09-10.550 [Info] (librespot_core::session) Connecting to AP "ap.spotify.com:443"
```
I'm able to resolve other addresses from within the container.

Any idea what could be happening here? Thanks in advance
